import React, { useState } from 'react';
import { useCRM } from '../context/CRMContext';
import { Plus, Check, LayoutDashboard, Bell, Trash2, TrendingUp } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { format } from 'date-fns';
import { pt } from 'date-fns/locale';

export default function Tasks() {
    const { tasks, clients, settings, addTask, toggleTaskCompletion, deleteTask, currentUser } = useCRM();
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [filter, setFilter] = useState<'all' | 'pending' | 'completed'>('all');

    // New Task Form State
    const [selectedClientId, setSelectedClientId] = useState('');
    const [selectedDefId, setSelectedDefId] = useState('');
    const [dueDate, setDueDate] = useState(new Date().toISOString().split('T')[0]);
    const [description, setDescription] = useState('');

    // Filter tasks for current user
    const userTasks = tasks.filter(t => t.userId === currentUser?.id);
    const userClients = clients.filter(c => c.userId === currentUser?.id);

    const filteredTasks = userTasks.filter(task => {
        if (filter === 'pending') return !task.completed;
        if (filter === 'completed') return task.completed;
        return true;
    }).sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime());

    const handleCreateTask = (e: React.FormEvent) => {
        e.preventDefault();
        const definition = settings.taskDefinitions.find(d => d.id === selectedDefId);
        if (!definition) return;

        addTask({
            clientId: selectedClientId || undefined,
            definitionId: definition.id,
            title: definition.title,
            description: description,
            dueDate: new Date(dueDate).toISOString(),
            completed: false,
            priority: definition.defaultPriority,
            autoGenerated: false
        });

        setIsModalOpen(false);
        resetForm();
    };

    const resetForm = () => {
        setSelectedClientId('');
        setSelectedDefId('');
        setDescription('');
        setDueDate(new Date().toISOString().split('T')[0]);
    }

    const handleAutoGenerate = () => {
        // Logic: Find clients with no tasks pending and no recent interaction (mock logic)
        // For this demo, we'll just check clients who don't have any pending task
        const clientsWithTasks = new Set(userTasks.filter(t => !t.completed).map(t => t.clientId));

        // Default task definition (first one or fallback)
        const def = settings.taskDefinitions[0];
        if (!def) return;

        let generatedCount = 0;

        userClients.forEach(client => {
            if (!clientsWithTasks.has(client.id)) {
                addTask({
                    clientId: client.id,
                    definitionId: def.id,
                    title: `Contactar ${client.companyName}`, // Dynamic title
                    description: 'Tarefa gerada automaticamente por inatividade.',
                    dueDate: new Date(Date.now() + 86400000 * 3).toISOString(), // +3 days
                    completed: false,
                    priority: 'medium',
                    autoGenerated: true
                });
                generatedCount++;
            }
        });

        if (generatedCount > 0) {
            alert(`${generatedCount} tarefas geradas automaticamente!`);
        } else {
            alert('Todas os clientes já têm tarefas pendentes.');
        }
    };

    const getPriorityColor = (priority: string) => {
        switch (priority) {
            case 'high': return 'text-red-600 bg-red-50 border-red-200';
            case 'medium': return 'text-amber-600 bg-amber-50 border-amber-200';
            default: return 'text-blue-600 bg-blue-50 border-blue-200';
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center flex-wrap gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-slate-800">Tarefas</h1>
                    <p className="text-slate-500">Gerencie as suas atividades diárias</p>
                </div>
                <div className="flex gap-2">
                    <Button variant="outline" onClick={handleAutoGenerate}>
                        <TrendingUp size={18} className="mr-2" />
                        Sugerir Tarefas
                    </Button>
                    <Button onClick={() => setIsModalOpen(true)}>
                        <Plus size={20} className="mr-2" />
                        Nova Tarefa
                    </Button>
                </div>
            </div>

            {/* Filters */}
            <div className="flex gap-2">
                <button
                    onClick={() => setFilter('all')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${filter === 'all' ? 'bg-slate-800 text-white' : 'bg-white text-slate-600 hover:bg-slate-50'}`}
                >
                    Todas
                </button>
                <button
                    onClick={() => setFilter('pending')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${filter === 'pending' ? 'bg-slate-800 text-white' : 'bg-white text-slate-600 hover:bg-slate-50'}`}
                >
                    Pendentes
                </button>
                <button
                    onClick={() => setFilter('completed')}
                    className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${filter === 'completed' ? 'bg-emerald-600/90 text-white' : 'bg-white text-slate-600 hover:bg-slate-50'}`}
                >
                    Concluídas
                </button>
            </div>

            {/* Task List */}
            <div className="grid gap-4">
                {filteredTasks.length === 0 ? (
                    <div className="text-center py-12 bg-white rounded-xl border border-dashed border-slate-300">
                        <Check className="mx-auto h-12 w-12 text-slate-300 mb-3" />
                        <h3 className="text-lg font-medium text-slate-900">Tudo em dia!</h3>
                        <p className="text-slate-500">Não existem tarefas para mostrar.</p>
                    </div>
                ) : (
                    filteredTasks.map(task => {
                        const client = clients.find(c => c.id === task.clientId);
                        const isOverdue = !task.completed && new Date(task.dueDate) < new Date(new Date().setHours(0, 0, 0, 0));

                        return (
                            <div key={task.id} className={`bg-white p-4 rounded-xl shadow-sm border ${task.completed ? 'border-emerald-100 bg-emerald-50/30' : 'border-slate-200'} flex items-center gap-4 group transition-all hover:shadow-md`}>
                                <button
                                    onClick={() => toggleTaskCompletion(task.id)}
                                    className={`flex-shrink-0 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors ${task.completed ? 'bg-emerald-500 border-emerald-500 text-white' : 'border-slate-300 text-transparent hover:border-emerald-400'}`}
                                >
                                    <Check size={14} strokeWidth={3} />
                                </button>

                                <div className="flex-1 min-w-0">
                                    <div className="flex items-center gap-2 mb-1">
                                        <h3 className={`font-semibold ${task.completed ? 'text-slate-500 line-through' : 'text-slate-800'}`}>{task.title}</h3>
                                        {isOverdue && (
                                            <span className="flex items-center gap-1 text-xs font-medium text-red-600 bg-red-50 px-2 py-0.5 rounded-full">
                                                <Bell size={12} /> Atrasada
                                            </span>
                                        )}
                                        <span className={`text-xs px-2 py-0.5 rounded-full border ${getPriorityColor(task.priority)}`}>
                                            {task.priority === 'high' ? 'Alta' : task.priority === 'medium' ? 'Média' : 'Baixa'}
                                        </span>
                                        {task.autoGenerated && (
                                            <span className="flex items-center gap-1 text-xs font-medium text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full">
                                                <TrendingUp size={10} /> Auto
                                            </span>
                                        )}
                                    </div>

                                    <div className="flex items-center gap-4 text-sm text-slate-500">
                                        {client && (
                                            <span className="flex items-center gap-1 font-medium text-slate-600">
                                                Empresa: {client.companyName}
                                            </span>
                                        )}
                                        <span className={`flex items-center gap-1 ${isOverdue ? 'text-red-600 font-medium' : ''}`}>
                                            <LayoutDashboard size={14} />
                                            {format(new Date(task.dueDate), "d 'de' MMMM", { locale: pt })}
                                        </span>
                                    </div>
                                    {task.description && (
                                        <p className="text-sm text-slate-400 mt-1 truncate">{task.description}</p>
                                    )}
                                </div>

                                <Button
                                    variant="ghost"
                                    size="sm"
                                    className="opacity-0 group-hover:opacity-100 text-red-500 hover:bg-red-50 hover:text-red-600"
                                    onClick={() => deleteTask(task.id)}
                                >
                                    <Trash2 size={16} />
                                </Button>
                            </div>
                        );
                    })
                )}
            </div>

            {/* Modal */}
            {isModalOpen && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-md p-6">
                        <h2 className="text-xl font-bold mb-4">Nova Tarefa</h2>
                        <form onSubmit={handleCreateTask} className="space-y-4">

                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-1">Tipo de Tarefa</label>
                                <select
                                    required
                                    className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500"
                                    value={selectedDefId}
                                    onChange={e => setSelectedDefId(e.target.value)}
                                >
                                    <option value="">Selecione o tipo...</option>
                                    {settings.taskDefinitions.map(def => (
                                        <option key={def.id} value={def.id}>{def.title}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-1">Cliente (Opcional)</label>
                                <select
                                    className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500"
                                    value={selectedClientId}
                                    onChange={e => setSelectedClientId(e.target.value)}
                                >
                                    <option value="">Nenhum</option>
                                    {userClients.map(c => (
                                        <option key={c.id} value={c.id}>{c.companyName}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-1">Data Limite</label>
                                <input
                                    type="date"
                                    required
                                    className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500"
                                    value={dueDate}
                                    onChange={e => setDueDate(e.target.value)}
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-slate-700 mb-1">Notas</label>
                                <textarea
                                    className="w-full px-3 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 h-24 resize-none"
                                    placeholder="Detalhes adicionais..."
                                    value={description}
                                    onChange={e => setDescription(e.target.value)}
                                />
                            </div>

                            <div className="flex justify-end gap-3 mt-6">
                                <Button type="button" variant="ghost" onClick={() => setIsModalOpen(false)}>Cancelar</Button>
                                <Button type="submit">Criar Tarefa</Button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
