export type ContactType = 'phone' | 'email' | 'meeting';
export type OpportunityStatus = 'open' | 'won' | 'lost';
export type ProductType = 'service' | 'product' | 'consulting';
export type UserRole = 'admin' | 'user';
export type TaskPriority = 'low' | 'medium' | 'high';
export type LeadStatus = 'new' | 'contacted' | 'qualified' | 'disqualified' | 'converted';
export type CampaignStatus = 'draft' | 'scheduled' | 'sent' | 'archived';

export interface SubContact {
    id: string;
    name: string;
    role: string;
    phone: string;
    email: string;
}

export interface User {
    id: string;
    name: string;
    email: string;
    password: string; // In a real app this would be hashed
    role: UserRole;
}

export interface TaskDefinition {
    id: string;
    title: string;
    defaultPriority: TaskPriority;
    daysToComplete: number; // For auto-scheduling
}

export interface Task {
    id: string;
    userId: string;
    clientId?: string;
    leadId?: string;
    definitionId?: string; // If created from a definition
    title: string;
    description: string;
    dueDate: string;
    completed: boolean;
    priority: TaskPriority;
    autoGenerated: boolean;
    createdAt: string;
}

export interface Client {
    id: string;
    userId: string;
    // Dados principais
    companyName: string;
    contactName: string; // Contacto principal
    nif?: string;
    phone: string;
    mobile?: string;
    email: string;
    address?: string;

    // Dados específicos
    clientNumber1?: string;
    clientNumber2?: string;
    paymentConditions: string;
    notes: string;

    // Relacionamentos
    subContacts: SubContact[];

    createdAt: string;
    updatedAt: string;
}

export interface Lead {
    id: string;
    userId: string;
    companyName: string;
    contactName: string;
    email: string;
    phone: string;
    source: string; // UTM, referral, event
    status: LeadStatus;
    score: number;
    notes: string;
    createdAt: string;
    convertedAt?: string;
    convertedClientId?: string;
}

export interface Interaction {
    id: string;
    userId: string;
    clientId?: string;
    leadId?: string;
    type: ContactType;
    date: string;
    summary: string;
    nextSteps?: string;
}

export interface Opportunity {
    id: string;
    userId: string;
    clientId: string;
    title: string;
    value: number;
    status: OpportunityStatus;
    stage: string; // Pipeline stage ID
    expectedDate?: string;
    createdAt: string;
}

export interface PipelineStage {
    id: string;
    name: string;
    order: number;
    probability: number; // 0-100
    color: string;
}

export interface Campaign {
    id: string;
    userId: string;
    name: string;
    subject: string;
    content: string; // HTML or Markdown
    status: CampaignStatus;
    sentAt?: string;
    metrics: {
        sent: number;
        opened: number;
        clicked: number;
        bounced: number;
    };
    targets: string[]; // Segment criteria or list of emails
    createdAt: string;
}

export interface AutomationWorkflow {
    id: string;
    name: string;
    trigger: {
        type: 'lead_created' | 'sale_completed' | 'status_changed';
        condition?: string;
    };
    actions: {
        type: 'send_email' | 'create_task' | 'update_field';
        params: any;
    }[];
    active: boolean;
}

export interface Document {
    id: string;
    userId: string;
    clientId?: string;
    opportunityId?: string;
    name: string;
    type: string; // PDF, DOCX, etc.
    url: string; // In mock, could be a base64 or placeholder
    version: number;
    createdAt: string;
}

export interface Sale {
    id: string;
    userId: string;
    clientId: string;
    date: string;
    value: number;
    productType: ProductType;
    description: string;
}

export interface ClassificationLevel {
    id: string;
    label: string;
    minSales: number;
    color: string;
}
